#!/usr/bin/env python3
# encoding: UTF-8

"""
Helper script to create a Profile object from a DAT file.

This script reads DAT files generated by Profile.generate_dat_file() and
reconstructs the Profile object. It's the reverse operation of the
generate_dat_file method.

Usage:
    python load_profile_from_dat.py <dat_file_path>

    # Or import and use in your code:
    from load_profile_from_dat import load_profile_from_dat
    profile = load_profile_from_dat("Shape_HR-54-116.dat")
"""

import sys
from pathlib import Path
from typing import Optional

# Add the current directory to the Python path to import python_magnetgeo
#sys.path.insert(0, str(Path(__file__).parent))

from python_magnetgeo.Profile import Profile


def load_profile_from_dat(dat_file_path: str) -> Profile:
    """
    Load a Profile object from a DAT file.

    Reads a DAT file created by Profile.generate_dat_file() and reconstructs
    the Profile object with the original data.

    Args:
        dat_file_path: Path to the .dat file to read

    Returns:
        Profile: Reconstructed Profile object

    Raises:
        FileNotFoundError: If the DAT file doesn't exist
        ValueError: If the file format is invalid

    Example:
        >>> profile = load_profile_from_dat("Shape_HR-54-116.dat")
        >>> print(profile.cad)
        HR-54-116
        >>> print(len(profile.points))
        7
    """
    dat_path = Path(dat_file_path)

    if not dat_path.exists():
        raise FileNotFoundError(f"DAT file not found: {dat_file_path}")

    cad = None
    points = []
    labels = []
    has_labels = False
    n_points = None

    # Try multiple encodings to handle different file formats
    # Prioritize encodings commonly used for French text files
    encodings = ["utf-8", "latin-1", "iso-8859-1", "cp1252", "windows-1252"]
    file_content = None
    successful_encoding = None

    for encoding in encodings:
        try:
            with open(dat_path, "r", encoding=encoding, errors='strict') as f:
                file_content = f.readlines()
            successful_encoding = encoding
            print(f'{dat_file_path}: Successfully read file with encoding: {encoding}', flush=True)
            break
        except (UnicodeDecodeError, LookupError) as e:
            print(f"Failed to read with encoding {encoding}: {e}", flush=True)
            continue

    if file_content is None:
        raise ValueError(f"Could not decode file {dat_file_path} with any of the supported encodings: {encodings}")

    # Extract CAD from filename as fallback (e.g., "Shape_HR-54-116.dat" -> "HR-54-116")
    filename = dat_path.stem  # Get filename without extension
    cad_from_filename = None
    if filename.startswith("Shape_"):
        cad_from_filename = filename[6:]  # Remove "Shape_" prefix

    cad = cad_from_filename  # Use filename CAD as default

    try:
        for line in file_content:
            line = line.strip()
            print(line, flush=True)

            # Skip empty lines
            if not line:
                continue

            # Parse CAD identifier from header
            if line.startswith("#Shape :"):
                cad = line.split(":", 1)[1].strip()
                print(f"Found CAD in file header: {cad}", flush=True)
                continue

            # Parse number of points
            if n_points is None and line.startswith("#N_i"):
                # Next non-comment line will be the count
                has_npts = True
                continue

            # Skip column headers
            if line.startswith("#"):
                # Check if this is the column header with Id_i
                if "Id_i" in line:
                    has_labels = True
                if "X_i" in line:
                    has_points = True
                continue

            # Parse the number of points
            if n_points is None:
                if has_npts:
                    n_points = int(line)
                    has_npts= False
                    continue

            # Parse data lines
            parts = line.split()
            if len(parts) >= 2:
                if has_points:
                    x = float(parts[0])
                    y = float(parts[1])
                    points.append([x, y])

                    # Check for label (third column)
                    if len(parts) >= 3:
                        label = int(parts[2])
                        labels.append(label)
                        has_labels = True
                    else:
                        labels.append(0)
                continue
    except Exception as e:
        raise ValueError(f"Error parsing DAT file: {e}")

    if not points:
        raise ValueError("No valid data points found in DAT file")

    # Ensure we have a CAD identifier (from file header or filename)
    if cad is None:
        raise ValueError("Could not determine CAD identifier from file header or filename")

    print(f"Using CAD identifier: {cad}", flush=True)

    # Check if we should include labels
    # Only include labels if explicitly present and not all zeros
    final_labels = None
    if has_labels and labels and any(label != 0 for label in labels):
        final_labels = labels

    # Create and return the Profile object
    return Profile(cad=cad, points=points, labels=final_labels)


def main():
    """
    Command-line interface for loading a Profile from a DAT file.

    Usage:
        python load_profile_from_dat.py <dat_file_path> [--yaml|--json]
    """
    import argparse

    parser = argparse.ArgumentParser(
        description="Load a Profile object from a DAT file",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Load and display profile info
  python load_profile_from_dat.py Shape_HR-54-116.dat

  # Load and export to YAML
  python load_profile_from_dat.py Shape_HR-54-116.dat --yaml

  # Load and save to YAML (HR-54-116.yaml)
  python load_profile_from_dat.py Shape_HR-54-116.dat --save-yaml

  # Load and export to JSON
  python load_profile_from_dat.py Shape_HR-54-116.dat --json
        """
    )

    parser.add_argument(
        "dat_file",
        help="Path to the DAT file to load"
    )

    output_group = parser.add_mutually_exclusive_group()
    output_group.add_argument(
        "--yaml",
        action="store_true",
        help="Output as YAML format"
    )
    output_group.add_argument(
        "--json",
        action="store_true",
        help="Output as JSON format"
    )
    output_group.add_argument(
        "--save-yaml",
        metavar="FILE",
        help="Save to YAML file"
    )
    output_group.add_argument(
        "--save-json",
        metavar="FILE",
        help="Save to JSON file"
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Show detailed information"
    )

    args = parser.parse_args()

    try:
        # Load the profile
        if args.verbose:
            print(f"Loading profile from: {args.dat_file}")

        profile = load_profile_from_dat(args.dat_file)
        dirname = Path(args.dat_file).parent
        basename = Path(args.dat_file).stem

        # Output based on flags
        if args.yaml:
            # Import yaml for string output
            import yaml
            print(yaml.dump(profile, default_flow_style=False))
        elif args.json:
            print(profile.to_json())
        elif args.save_yaml:
            # Save to specified YAML file
            import yaml
            output_path = Path(args.save_yaml)
            profile.dump()
            print(f"Saved YAML to: {args.save_yaml}/{profile.cad}.yaml")
        elif args.save_json:
            output_path = Path(args.save_json)
            profile.to_json(output_path)
            print(f"Saved JSON to: {args.save_json}")
        else:
            # Default: show profile information
            print(f"Profile loaded successfully!")
            print(f"  CAD: {profile.cad}")
            print(f"  Points: {len(profile.points)}")
            print(f"  Has labels: {profile.labels is not None and any(label != 0 for label in profile.labels)}")

            if args.verbose:
                print(f"\nProfile representation:")
                print(f"  {profile!r}")
                print(f"\nFirst 5 points:")
                for i, (point, label) in enumerate(zip(profile.points[:5], profile.labels[:5]), 1):
                    print(f"    {i}. [{point[0]:.2f}, {point[1]:.2f}] label={label}")
                if len(profile.points) > 5:
                    print(f"    ... and {len(profile.points) - 5} more points")

        return 0

    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"Error parsing DAT file: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Unexpected error: {e}", file=sys.stderr)
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1


if __name__ == "__main__":
    # Run some examples if no arguments provided
    if len(sys.argv) == 1:
        print("=== Profile DAT File Loader ===")
        print()
        print("This script loads Profile objects from DAT files.")
        print()
        print("Usage:")
        print("  python load_profile_from_dat.py <dat_file> [options]")
        print()
        print("Run with --help for more information")
        print()
        print("=== Creating example DAT files for demonstration ===")

        # Create example profiles and DAT files
        example1 = Profile(
            cad="EXAMPLE-WITH-LABELS",
            points=[
                [-5.34, 0.0],
                [-3.34, 0.0],
                [-2.01, 0.9],
                [0.0, 0.9],
                [2.01, 0.9],
                [3.34, 0.0],
                [5.34, 0.0],
            ],
            labels=[0, 0, 0, 1, 0, 0, 0],
        )

        example2 = Profile(
            cad="EXAMPLE-NO-LABELS",
            points=[
                [0.0, 0.0],
                [0.5, 0.05],
                [1.0, 0.03],
                [1.5, 0.0],
            ],
            labels=None,
        )

        # Generate DAT files
        file1 = example1.generate_dat_file()
        file2 = example2.generate_dat_file()

        print(f"Created: {file1}")
        print(f"Created: {file2}")
        print()

        # Load them back
        print("=== Loading examples back ===")
        loaded1 = load_profile_from_dat(str(file1))
        print(f"\nLoaded {loaded1.cad}:")
        print(f"  Points: {len(loaded1.points)}")
        print(f"  Has meaningful labels: {loaded1.labels is not None and any(l != 0 for l in loaded1.labels)}")

        loaded2 = load_profile_from_dat(str(file2))
        print(f"\nLoaded {loaded2.cad}:")
        print(f"  Points: {len(loaded2.points)}")
        print(f"  Has meaningful labels: {loaded2.labels is not None and any(l != 0 for l in loaded2.labels)}")

        print("\n=== Verification ===")
        print(f"Example 1 matches: {example1.cad == loaded1.cad and example1.points == loaded1.points}")
        print(f"Example 2 matches: {example2.cad == loaded2.cad and example2.points == loaded2.points}")

        sys.exit(0)
    else:
        sys.exit(main())
